### ISSUE TITLE
RedirectURI does not work for router with PathPrefix

### ISSUE THREAD

**Issue by KampfCaspar** [wdonne/traefikoidc#4]
If I have a router with Host an PathPrefix as rules, the callback URL is created w/o the PathPrefix - therefore the middleware is never reached after authentication... 

It is - of course - possible to duplicate the middleware requirement on a second router without the PathPrefix. It would be nice, however, to be able to add the PathPrefix both to the callback URL and the Cookie Path. That would 'fit better' in the router system...

**Comment by wdonne** [comment]
@KampfCaspar You are right. There should be a configuration field to set the context path and its value should be used for the callback, the cookie and the internal logout path. It will be added.

**Comment by wdonne** [comment]
Fixed in v1.1.0.
