### ISSUE TITLE
Bearer token header doesn't work from Postman

### ISSUE THREAD

**Issue by phrontizo** [wdonne/traefikoidc#6]
I was testing this plugin with Postman, and discovered that using a bearer token always results in an "invalid token" issue and redirection to login. The issue seems to be:
https://github.com/wdonne/traefikoidc/blob/28879155397541f8dfe8e05a9ce1bca36c2c2b13/oidc.go#L273

I think the string should be split on a space rather than empty string.

**Comment by wdonne** [comment]
You are right. It always falls back to the cookie because of this. Thanks for reporting.

**Comment by wdonne** [comment]
Fixed in v1.1.0.
